package com.huangshihe.rt.model;

import com.huangshihe.rt.model.base.BaseUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class User extends BaseUser<User> {
	public static final User dao = new User();

    public static User verify(User toVerify) {
        return dao.findFirst("select * from user where username=? and password=?", toVerify.getUsername(), toVerify.getPassword());
    }

    public static User getUser(int userId){
        return User.dao.findFirstByCache("userList", "user" + userId,
                "select * from user where id=?", userId);
    }
}